### ISSUE TITLE
Failed to run test suite by using jest  

### ISSUE THREAD

**Issue by VachaganGrigoryan** [bnb-chain/javascript-sdk#406]
Test suite failed to run when using Github Actions, getting following error
 
```
TypeError: Cannot redefine property: configDescriptor
        at Function.defineProperty (<anonymous>)
    > 1 | import { BncClient, crypto } from "@binance-chain/javascript-sdk";
        | ^
      2 |
      3 | const network = "mainnet";
      at Object.<anonymous> (node_modules/usb/usb.js:54:8)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/src/listenDevices.js:6:1)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/src/TransportNodeHid.js:14:1)
      at Object.<anonymous> (node_modules/@binance-chain/javascript-sdk/lib/ledger/index.js:41:74)
      at Object.<anonymous> (node_modules/@binance-chain/javascript-sdk/lib/index.js:57:38) 
```
Is there any solution for this.

Here is my workflow file

```
...
jobs:
  Build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Install Ubuntu dependencies
        run: sudo apt-get install -y libudev-dev libusb-dev usbutils
      ....
      - name: Install dependencies
        run: yarn install
      
      - name: Lint code
        run: yarn lint

      - name: Test code
        run: yarn test
```
